### PR TITLE
issue #565 highlight during annotation

### PR DESCRIPTION
**Pull request by ams10961**
The following updated highlights selected text during annotation instead of just before and after.
A solution to issue #565

### CODE REVIEW

**Comment by tilgovi** [comment]
Looks like you included changes to `checkOrientation` here that are a different issue.

Also, if you could remove code rather than commenting it out, that's much better. If we want it back, that's what git is for :).

I would leave the `annotationCreated` callback there though as extra documentation even if it's empty, since `main.js` is supposed to be the example application.

**Comment by tilgovi** [comment]
Thanks!

**Comment by ams10961** [comment]
hi .. the checkOrientation changes should not have been there; I added
those after the pull request; can you selectively accept/reject? if so,
please reject checkOrientation, if not, I'll try to remove.

**Comment by tilgovi** [comment]
It's not possible for me to selectively merge parts of a PR.

It would be best if you closed this PR and created two branches, one for your check orientation fix and one for your highlight fix.

On each of these, resolving the differences should be easy:

```bash
$ git pull --rebase origin/master
[ substitute for origin whatever you called this openannotation/annotator remote ]
[ this will ensure you're working with the latest changes ]

$ git checkout -b check-orientation-fix
[ This will copy your current master to a new check-orientation-fix branch ]

$ git checkout -b highlight-fix
[ This will do the same, with a new highlight-fix branch ]

$ git reset origin/master
[ Now you have your index for the highlight-fix branch pointing at master ]
[ It's as if you made no commits, but have all the changes locally ]

$ git add -p
[Use -p for interactive prompts, or git add <filename> and just add what you want ]

$ git commit -m "Show highight while annotating"
[ Now you've got a branch, highlight-fix, with just one commit that you want ]
```

Then, you can check out your check-orientation-fix branch and do the same reset/add dance to just get what you want. Push them both to separate branches and open two PRs.

**Comment by ams10961** [comment]
ok, I'll withdraw this request, and reattempt.

**Pull request closed without merging**
