### PR TITLE
WIP: AnnotateIt.org Firefox Add-on

### PR DESCRIPTION
**Pull request by BigBlueHat**
Early stage Firefox Add-on attempt.

Regardless, would love some input, feedback, and/or help. :smile: 

#### Know Issues
* experimental
* not currently built with build scripts, but **definitely** should be
* in-page notifications are annoying
* doesn't support Firefox's < 29
* only tested in Firefox 31 (latest released atm)

### CODE REVIEW

**Comment by nickstenning** [comment]
Going to close this for now. Let's focus our efforts on the Hypothesis FF extension.

**Comment by BigBlueHat** [comment]
So...this extension is actually already available on Moz Addons:
https://addons.mozilla.org/en-US/firefox/addon/annotate-it/

I've submitted it for a "full review" (#9 in the queue atm), so it should be a less scary install process soon.

Lastly, the Annotator community includes far more than just folks from Hypothes.is, so I'm not sure it's safe to say "Let's focus our efforts..." and point people away from an AnnotateIt.org extension--which is essentially what this is (vs. a more customizable AnnotatorJS.org extension).

At any rate, the extension does work, and it'd be good for the code to live somewhere so someone could take it farther--and I hope someone does. :smiley: 

As such, could we reopen this issue and (ideally) get this merged, so it can have a future?

Thanks!

**Comment by nickstenning** [comment]
@BigBlueHat I'm not sure what you want me to do here.

You opened it, marked as "WIP", eight months ago. There have been pending unaddressed review comments for seven. We manifestly do not have the time to maintain this. If you find the time to polish it up, feel free to reopen it.

**Comment by BigBlueHat** [comment]
Eh. No worries. I don't have time to dig into the build scripts to get fix the duplicated built assets thing properly, so...whatever. I may come back here when I have more time.

Hopefully someone else will care more sooner. :smile:

**Pull request closed without merging**
