### PR TITLE
point to new project location at https://annotator.apache.org/

### PR DESCRIPTION
**Pull request by jhpoelen**
Hi!

I have a suspicion that this repo is succeeded by https://annotator.apache.org/ . 

If so, suggest to include this in the readme . 

thx,
-jorrit

### CODE REVIEW

**Comment by TylerRick** [comment]
Are that really a continuation of this project though? I can't seem to find any evidence that it is.

https://github.com/openannotation/annotator/issues/667#issuecomment-399724007 says it is a "new suite":
> If anyone is interested, I've been working with others to boot up a new suite of annotation tools under the Apache Annotator (inbuating) project over here: https://annotator.apache.org/

The https://github.com/apache/incubator-annotator repo doesn't appear to be based on https://github.com/openannotation/annotator.
- https://github.com/apache/incubator-annotator only goes back to 2017-04-22
- https://github.com/openannotation/annotator goes back to 2009-07-19

The have different licences:
- https://github.com/apache/incubator-annotator/blob/master/LICENSE is Apache and goes back to 2017
- https://github.com/openannotation/annotator/blob/master/LICENSE is GPL and goes back to 2011

I must conclude that they are independent projects that just happen to share the same name. (But I don't know for sure.)

**Comment by tilgovi** [comment]
Independent projects. They share some contributors, and Apache Annotator was inspired by this work. It may still be appropriate to point folks to Apache Annotator, but I don't want to make that decision unilaterally right now. This project is in maintenance mode. If people want to step up to maintain it, it makes sense for it to persist independently. If not, then probably we should point folks toward something maintained.

**Comment by marclaporte** [comment]
@tilgovi What are current thoughts on the topic?

**Comment by jhpoelen** [comment]
ok, thanks for clarifying. Please feel free to close this issue.

**Pull request closed without merging**
