### PR TITLE
fixes issue with selection containing no Text in latest html node

### PR DESCRIPTION
**Pull request by jjmerillon**

### CODE REVIEW

**Comment by nickstenning** [comment]
Interesting. Are you able to provide a test case (see [this file](https://github.com/openannotation/annotator/blob/v1.2.x/test/spec/range_spec.coffee)) that demonstrates the problem this change fixes?

If you're not sure how to do that, no worries. If you could provide an example HTML document or some example of the bug, that would help us write the test case.

**Comment by BigBlueHat** [comment]
Any more info on this patch, @jjmerillon (per @nickstenning comment above)?

Seems you're dealing with markup that changes during/after selection? maybe? I'm guessing. :smile: 

Thanks!

**Comment by tilgovi** [comment]
I'm going to close this after some inactivity. This code has been separated out into xpath-range at this point and 2.0 is close and we still don't have a test case for this.

**Comment by tilgovi** [comment]
In fact, this fix is already implemented over there.

**Comment by tilgovi** [comment]
Actually, I found it. openannotation/xpath-range@d318ba7589a806735a727e9b9c4db4d0cae01e7e and it has a test. I'll backport it.

**Comment by tilgovi** [comment]
It was also on the master branch, it turns out. Anyway, I cherry-picked it to v1.2.x which was easy because this happened before we switched away from CoffeeScript.

**Pull request closed without merging**
