### PR TITLE
Adding hook for setting identity in SimpleIdentityPolicy

### PR DESCRIPTION
**Pull request by ianjevans**
Modified identity.js so it sets the user before an annotation is created.

### CODE REVIEW

**Comment by tilgovi** [comment]
Awesome. Thank you.

Would you mind adding a test for this in `test/spec/identity_test.js`? Or if you need help doing that I can add it.

**Comment by ianjevans** [comment]
Took a look at the test, and can't really see what would need to be
modified. The test should assert that the user is set during the
beforeAnnotationCreated and annotationCreated hooks.

**Comment by tilgovi** [comment]
I'll take from your branch and give it a shot.

**Comment by tilgovi** [comment]
Thanks.

**Comment by tilgovi** [comment]
I fixed your PR to use `.who()` (the public interface way to get the underlying identity) and added tests (7c235e2cd85c03aecb934920772d79e4f5caa567 and 5ef5edf157fe728b2d6d95d01e26a55c508c0c44).

**Pull request closed without merging**
