### PR TITLE
Remove util.getGlobal()

### PR DESCRIPTION
**Pull request by tilgovi**
Browserify does the right thing with `global`.

### CODE REVIEW

**Comment by BigBlueHat** [comment]
@tilgovi still planning to merge this?

Looks like the build failures are Sauce Labs related...not code. So that's good. :smiley:

**Comment by tilgovi** [comment]
Bump. Should resolve #542 as well, I hope.

**Comment by tilgovi** [comment]
Oops.

**Comment by tilgovi** [comment]
I didn't mean to merge this. But I did. Ah, well. I think it should be fine.

**Pull request merged**
