### PR TITLE
Registry rejig

### PR DESCRIPTION
**Pull request by nickstenning**
There's quite a bit in here. Sorry, I got a little carried away, but this does what I suggested I might do and turns the registry into a more zope-like application registry, and starts to do away with the idea of a "lifecycle" plugin, in favour of something that looks much more like a "module". `App` has an `include` method, which behaves much like Pyramid's `Configurator#include`.

Also a bunch of renaming for consistency. Plugins are now lowercased.

### CODE REVIEW

**Comment by nickstenning** [comment]
Suggest checking out and viewing with `diff -C`.

**Comment by tilgovi** [comment]
Looks great. A couple small lint errors need fixing.

**Comment by nickstenning** [comment]
Fixed!

**Comment by tilgovi** [comment]
Stage 1 Zope infection completed.

**Pull request merged**
