### PR TITLE
Add undrawAll & forAll methods to Highlighter

### PR DESCRIPTION
**Pull request by BigBlueHat**
forAll accepts a callback and is used as the foundation
of both drawAll and undrawAll.

### CODE REVIEW

**Comment by gergely-ujvari** [comment]
LGTM, but let's wait for the tests.

**Comment by BigBlueHat** [comment]
Fixed a lint issue. Non-PhantomJS browsers are still down at Travis / Sauce. :( No idea why...

**Comment by BigBlueHat** [comment]
FWIW the build failures here are Travis break downs ('can't find Chrome' etc)...not test failures.

**Comment by nickstenning** [comment]
Closing this for now.

**Pull request closed without merging**
